cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableInlineBuilds: true

enableScripts: true

networkConcurrency: 1

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
