# GitHub Actions workflow to build and deploy to GitHub Pages
# This workflow runs on push to the main branch

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'public/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'package.json'

      - name: Install corepack (for Yarn Berry)
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            tmp
            dist
            public/js
            public/css
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock', 'package.json', 'tsconfig.json', 'babel.config.js') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Copy libs to public/node_modules
        run: |
          mkdir -p public/node_modules/tesseract.js
          cp -r node_modules/tesseract.js/dist/* public/node_modules/tesseract.js/

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
